sudo: required

language: c++

services:
  - docker

before_install:
  - docker build . -t ${TRAVIS_REPO_SLUG}

script:
  - docker run -t ${TRAVIS_REPO_SLUG}
  
branches:
  only:
  - master
